# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksail < Formula
  desc ""
  homepage ""
  version "5.8.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.8.3/ksail_5.8.3_darwin_arm64.tar.gz"
      sha256 "a86c2476488981e5ae8b30412838b41c6075e24c7d1e99ed1b70962c8ea81f4d"

      def install
        bin.install "ksail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.8.3/ksail_5.8.3_linux_amd64.tar.gz"
      sha256 "51395c246a5760ed838c8d572d4488a4bb7cbb256c73cdb4c968d4674ae8ba82"
      def install
        bin.install "ksail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.8.3/ksail_5.8.3_linux_arm64.tar.gz"
      sha256 "155328062412f8b9e92daf171bc9c45303d4fcbdf658f2fc4d52f52a14d55688"
      def install
        bin.install "ksail"
      end
    end
  end
end
