# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail" do
  name "ksail"
  desc ""
  homepage ""
  version "5.20.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksail"

  on_macos do
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
      sha256 "b95256b345d84a1c4d8b96fc556aea86215cd6cf967a62a949d2bc587d345c72"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_amd64.tar.gz"
      sha256 "0ff76dcf4af34cf8c4d3ce09dc3ee5ec891362668a6e3254d42bc263c66a0da3"
    end
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_arm64.tar.gz"
      sha256 "f1dd9ed3275d8399c9ef224134414a9505e46b724109dd97f432e5c7db4586de"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksail"]
    end
  end

  # No zap stanza required
end
