# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail" do
  name "ksail"
  desc ""
  homepage ""
  version "5.19.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksail"

  on_macos do
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
      sha256 "34daef66f9d1be9368c48a18ff9fc5639a8c6b803717b6e1e8fac42cc9dcba20"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_amd64.tar.gz"
      sha256 "609cf406a0f8914125520dbe3fefdb58db4418c87fcef4995246816c168b9594"
    end
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_arm64.tar.gz"
      sha256 "3985a372b00395d042526a82bd6e4b81686a2b20c5e5ee75fc095c1ced416f29"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksail"]
    end
  end

  # No zap stanza required
end
