# This file was generated by GoReleaser. DO NOT EDIT.
cask "ksail" do
  name "ksail"
  desc ""
  homepage ""
  version "5.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ksail"

  on_macos do
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_darwin_arm64.tar.gz"
      sha256 "f0428dc129be0e2bb7356f8ee508fcbd4fb4a4197ff175683cbc32bab44fcb49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_amd64.tar.gz"
      sha256 "140519fe5db055d2a4fb2e47fb6c2642a017285aed28c3f7cdbcfd77a17c0a0d"
    end
    on_arm do
      url "https://github.com/devantler-tech/ksail/releases/download/v#{version}/ksail_#{version}_linux_arm64.tar.gz"
      sha256 "565fbfd84d95aa47edd4f067fba646075c2396f675885c2896a081b5625119be"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ksail"]
    end
  end

  # No zap stanza required
end
