# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksail < Formula
  desc "CLI tool to manage clusters and workloads"
  homepage "https://github.com/devantler-tech/ksail"
  version "5.8.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.8.1/ksail_5.8.1_darwin_arm64.tar.gz"
      sha256 "96c2c55aafc98d54848cd5b817e6e0215f311e6bb23616b9f39c1cd2a1203560"

      def install
        bin.install "ksail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.8.1/ksail_5.8.1_linux_amd64.tar.gz"
      sha256 "8992b3e400dec5a80b23372d6142f32b0d621859c38ddfc5699d08910b03bc23"
      def install
        bin.install "ksail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.8.1/ksail_5.8.1_linux_arm64.tar.gz"
      sha256 "c6eba521db60493429f4386352e4b1c2d2325c12925881ee5727cb5055e04dbd"
      def install
        bin.install "ksail"
      end
    end
  end

  def install
    bin.install "ksail"
  end

  test do
    system bin/"ksail", "--help"
  end
end
