# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksail < Formula
  desc "CLI tool to manage clusters and workloads"
  homepage "https://github.com/devantler-tech/ksail"
  version "5.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.5.0/ksail_5.5.0_darwin_arm64.tar.gz"
      sha256 "067598f4763f2ca36717fed1969cfbdb2d000278a08edf7cf12b9b9b4fe9e0dd"

      def install
        bin.install "ksail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.5.0/ksail_5.5.0_linux_amd64.tar.gz"
      sha256 "437d9cfefc120789bc072696ff0958209a120c777d324ad550149a2d887c6850"
      def install
        bin.install "ksail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devantler-tech/ksail/releases/download/v5.5.0/ksail_5.5.0_linux_arm64.tar.gz"
      sha256 "23a1ae8662b8bf6a2626f3e4a3afd6319454242d7798e76778f3033910450c61"
      def install
        bin.install "ksail"
      end
    end
  end

  def install
    bin.install "ksail"
  end

  test do
    system bin/"ksail", "--help"
  end
end
